
/* TEMP */
#define PROPERTY_TEMP_WATER 0
#define PROPERTY_TEMP_HC 1
#define PROPERTY_TEMP_TANK 2

/* IO */
#define PROPERTY_PUMP_HC 10
#define PROPERTY_PUMP_WATER 11
#define PROPERTY_FLOW_SWITCH 12
